### ISSUE TITLE
Reconnect does not work

### ISSUE THREAD

**Issue by otila** [cryptozoidberg/boolberry#34]
When there is a long network outage, boolbd fails to automatically connect to nodes. print_cn shows zero nodes.

**Comment by paulie-g** [comment]
or.. Maintain inactive nodes in a fifo queue and, once you hit a certain low threshold, start popping nodes off the queue and retrying them.

**Comment by clintar** [comment]
I'd suggest lifo so most recently seen gets tried first, but yeah.
