### ISSUE TITLE
Administrational Issue

### ISSUE THREAD

**Issue by mbe24** [cryptozoidberg/boolberry#50]
Sorry for highjacking this issue. 

There have been some people impersonating you on bbrproject.slack.com. I will ban anone assuming your identity. Contact me, when you want to join.

**Comment by longlegluvak** [comment]
There is only one official slack of the project: boolberry.slack.com

**Comment by cryptozoidberg** [comment]
There is only one official slack of the project: boolberry.slack.com

**Comment by mbe24** [comment]
Np, not relevant anymore!
