### ISSUE TITLE
scratchpad saving option

### ISSUE THREAD

**Issue by clintar** [cryptozoidberg/boolberry#57]
Hi, I'd like to have the ability to change the frequency or turn off blockchain saving, since it blocks access to daemon's rpc calls. I could run another daemon on a different machine that saves periodically and just sync that over instead.

**Comment by clintar** [comment]
Why did I call this scratchpad saving?

**Comment by sowle** [comment]
Since the blockchain was moved to DB this seems not to be an issue anymore.
@clintar can you confirm, please?

**Comment by clintar** [comment]
Yes, not an issue anymore
