### ISSUE TITLE
Build fails on gcc7 with -Werror

### ISSUE THREAD

**Issue by paulie-g** [cryptozoidberg/boolberry#59]
Similar to a lot of other bytecoin-derived coins, the build fails on gcc7. The kludge is to remove -Werror. Up to you if you want to do something more substantive about it, but most rolling-release distros are on gcc7 now so it ought not just be ignored.

**Comment by clintar** [comment]
What error do you get

**Comment by paulie-g** [comment]
There are a lot of them. GCC7 spits out a lot of new warnings, which are upgraded to errors because of -Werror and not individually excluded with -Wno.. flags. It's a bit silly for me to compile a list since that duplicates the effort that would anyway be required to fix the warnings properly.

**Comment by paulie-g** [comment]
Have a look at: https://github.com/Barro/compiler-warnings/blob/master/gcc/warnings-gcc-diff-6-7.txt

Of those, I recall seeing implicit fallthrough for switch statements and stringop overflow (mis)detections most in this and other codebases I've filed gcc7 bugs for (cryptonote variants).

**Comment by paulie-g** [comment]
Keep in mind that it's just the gcc6 to 7 diff, the diff for 4-latest to 7 is going to be bigger (and is available on that git repo in pieces as well)

**Comment by cryptozoidberg** [comment]
Thanks for reporting this issue, i'll take care about this in neared days.

**Comment by clintar** [comment]
Can you verify it works now on your build environment? There were fixes that look to be related to this.

**Comment by sowle** [comment]
I fixed compilation issues I had had on gcc 7.2 and MSVC 2017 (15.5.7) and it looks like CZ approved my PR with that fix.
Please, try to build it again.

**Comment by sowle** [comment]
-Werror is not used anymore.
build succeeds on gcc 7.2 with on issues.
