### ISSUE TITLE
Build fails on gcc7 (Serialization macros)

### ISSUE THREAD

**Issue by paulie-g** [cryptozoidberg/boolberry#60]
/home/paul/sw/mining/bbr/src/boolberry/src/serialization/serialization.h: In member function ‘bool serializable_pair<first_type, second_type>::do_serialize_object(Archive<W>&)’:
/home/paul/sw/mining/bbr/src/boolberry/src/serialization/serialization.h:110:11: error: ‘first’ was not declared in this scope
     FIELD(first)

I looked at the preprocessor's output and I'm not sure how this ever compiled, so not sure how to fix. I'm not a c++ guy though.

**Comment by d3m0n0gr4ph1c** [comment]
I have the same issue. That code is 10 days old so it was compiling up until then I guess.

**Comment by clintar** [comment]
This is fixed

**Comment by cryptozoidberg** [comment]
Thanks for report!
