### ISSUE TITLE
Error during synchronization. Orphan block

### ISSUE THREAD

**Issue by pedrojioc** [cryptozoidberg/boolberry#62]
2018-Feb-21 18:42:56.511637 [P2P7][88.99.228.50:10101 OUT]Sync data returned unknown top block: 791532 -> 983888 [192356 blocks (267 days) behind] 
SYNCHRONIZATION started
2018-Feb-21 18:42:56.511858 [P2P7][88.99.228.50:10101 OUT] COMMAND_HANDSHAKE INVOKED OK
2018-Feb-21 18:42:56.512423 [P2P6]Connecting to 193.111.239.66:10101(white=0, last_seen: d78.h11.m41.s27)...
2018-Feb-21 18:42:58.008330 [P2P7]ERROR /home/ubuntu/boolberry/src/currency_core/blockchain_storage.cpp:921[bool currency::blockchain_storage::complete_timestamps_vector(uint64_t, std::vector<long unsigned int>&)]internal error: passed start_height = 791532 not less then m_blocks.size()=791532
2018-Feb-21 18:42:58.008499 [P2P7]ERROR /home/ubuntu/boolberry/src/currency_core/blockchain_storage.cpp:1006[bool currency::blockchain_storage::handle_alternative_block(const currency::block&, const crypto::hash&, currency::block_verification_context&)]INTERNAL ERROR: Wrong bei.scratch_offset==0 in handle_alternative_block
2018-Feb-21 18:42:58.008644 [P2P7]Block recognized as orphaned and rejected, id = <e873826380deb38a09e2587b1fc5c6a27934eda8c676b7fd4d0cc0dc9b64995e>
2018-Feb-21 18:42:58.008752 [P2P7][5.9.44.190:10101 OUT]Block received at sync phase was marked as orphaned, dropping connection
2018-Feb-21 18:42:58.008860 [P2P7]Ip 5.9.44.190 blocked.
2018-Feb-21 18:42:58.502135 [P2P8]ERROR /home/ubuntu/boolberry/src/currency_core/blockchain_storage.cpp:921[bool currency::blockchain_storage::complete_timestamps_vector(uint64_t, std::vector<long unsigned int>&)]internal error: passed start_height = 791532 not less then m_blocks.size()=791532
2018-Feb-21 18:42:58.502304 [P2P8]ERROR /home/ubuntu/boolberry/src/currency_core/blockchain_storage.cpp:1006[bool currency::blockchain_storage::handle_alternative_block(const currency::block&, const crypto::hash&, currency::block_verification_context&)]INTERNAL ERROR: Wrong bei.scratch_offset==0 in handle_alternative_block
2018-Feb-21 18:42:58.502445 [P2P8]Block recognized as orphaned and rejected, id = <e873826380deb38a09e2587b1fc5c6a27934eda8c676b7fd4d0cc0dc9b64995e>
2018-Feb-21 18:42:58.502549 [P2P8][88.99.228.50:10101 OUT]Block received at sync phase was marked as orphaned, dropping connection

**Comment by sowle** [comment]
DB seems to be out-of-sync for some reason. You may be needed to update the daemon to latest version and re-sync from scratch.
