### ISSUE TITLE
Wallet throws an error

### ISSUE THREAD

**Issue by sylido** [cryptozoidberg/boolberry#66]
I'm getting `Status: Failed to initialize core` when starting the app after it tries to sync for 5 seconds. Is there a flag or anything I can add to the shortcut to trigger re-sync ? Any other solution to this issue ?

Not running any firewalls or antivirus software that might be blocking the connection. It did fully sync yesterday without any trouble.

**Comment by sowle** [comment]
@sylido are you still experiencing this issue?
