### ISSUE TITLE
Blockchain database

### ISSUE THREAD

**Issue by pcdinh** [cryptozoidberg/boolberry#7]
It would be great if BoolBerry can store blockchain into an embedded database like Sophia, the fatest one at the moment https://github.com/pmwkaa/sophia (much faster than LevelDB).

The problem with our current data store is that the Boost serialization is not cross platform compatible.

Sophia will make cross platform compatibility a breeze. Also, there is some third party libraries for Sophia already, which helps developers build apps on top of it easily. It should expand BoolBerry ecosystem a lot.

Ref: http://sphia.org/get.html

**Comment by sowle** [comment]
Boolberry now uses LMDB as blockchain storage.
