### ISSUE TITLE
128 bit difficulty checks are buggy

### ISSUE THREAD

**Issue by moneromooo-monero** [cryptozoidberg/boolberry#91]
While looking at Boolberry's 128 bit difficulty patch to use it in Monero, I noticed it has a few bugs. See https://github.com/monero-project/monero/pull/5239 which hopefully is all fixed. Mostly:
- hashVal << 64  should be  hashVal <<= 64
- hashVal <<= 64  should be swapped with the other line in the loop
- hashVal * difficulty > max256bit  should be  hashVal * difficulty <= max256bit

I think that's it, but I did not build Boolberry so can't be sure. I also extended the tests to test the 128 bit area (see the PR above), which found all these. Feel free to copy.

**Comment by cryptozoidberg** [comment]
Oh damn... needed so much talent to make 3 bugs in 3 lines! 👍  
Thanks for pointing that, it's much appreciated! 
Fixed it in c82f93a
